tap "epk/epk"
tap "homebrew/bundle"
tap "homebrew/services"
tap "powershell/tap"
tap "shaunsingh/sfmono-nerd-font-ligaturized"
brew "exiftool"
brew "logrotate", restart_service: true
brew "ncurses"
brew "p7zip"
brew "ripgrep"
brew "unzip"
brew "wget"
brew "z3"
